env:
  commonjs: true
  es2021: true
  jest: true

extends:
  - airbnb-base
  - plugin:promise/recommended

parserOptions:
  ecmaVersion: 12

plugins:
  - import
  - promise

rules:
  semi: [error, never]
  indent: [error, 4]
  comma-dangle: [error, never]
  dot-notation: off
  no-plusplus: warn
  no-unused-vars: warn
  import/order: [error, {
    groups: ['builtin', 'external', 'internal', 'parent', 'sibling', 'index'],
    newlines-between: 'always',
    alphabetize: {
      order: 'asc',
      caseInsensitive: true
    }
  }]
  no-underscore-dangle: [error, {
    allowAfterThis: true
  }]
  newline-per-chained-call: off
  no-param-reassign: warn
